version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
      SECRET_KEY: 'tajny_klucz'
      SQLALCHEMY_DATABASE_URI: 'sqlite:///site.db'
