"""Initial migration

Revision ID: 1556bd8676e8
Revises: b25f48c90495
Create Date: 2024-01-23 18:58:19.158373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1556bd8676e8'
down_revision = 'b25f48c90495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('encrypted')

    # ### end Alembic commands ###
