"""Initial migration

Revision ID: 3405f9b4270e
Revises: 5a6ed6a0cc8a
Create Date: 2024-01-23 17:50:08.430178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3405f9b4270e'
down_revision = '5a6ed6a0cc8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('encrypted_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_content', sa.BLOB(), nullable=True))
        batch_op.drop_column('encrypted')

    # ### end Alembic commands ###
