"""Initial migration

Revision ID: 5a6ed6a0cc8a
Revises: 48fcd3c0380d
Create Date: 2024-01-23 17:45:30.127919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a6ed6a0cc8a'
down_revision = '48fcd3c0380d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_content', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('encrypted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted', sa.BLOB(), nullable=True))
        batch_op.drop_column('encrypted_content')

    # ### end Alembic commands ###
