"""Initial migration

Revision ID: 66095f000d32
Revises: 3405f9b4270e
Create Date: 2024-01-23 18:02:27.226800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66095f000d32'
down_revision = '3405f9b4270e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_content', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('encrypted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted', sa.BLOB(), nullable=True))
        batch_op.drop_column('encrypted_content')

    # ### end Alembic commands ###
