"""Initial migration

Revision ID: b25f48c90495
Revises: 66095f000d32
Create Date: 2024-01-23 18:44:09.364888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25f48c90495'
down_revision = '66095f000d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('encrypted_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_content', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
